query getChaptersByName($name: String, $limit: Int, $offset: Int) {
  chapter_aggregate(
    where: {
      _or: [{ title: { _ilike: $name } }, { author: { _ilike: $name } }]
    }
  ) {
    aggregate {
      count
    }
  }
  chapter(
    where: {
      _or: [{ title: { _ilike: $name } }, { author: { _ilike: $name } }]
    }
    order_by: { order: asc }
    limit: $limit
    offset: $offset
  ) {
    id
    title
    author
    order
    imageUrl
    Chapter_Book {
      title
    }
    bookId
  }
}